version: "3"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/usr/src/app
    environment:
      - API_URL=http://localhost:8081/

  server:
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/usr/src/app
